### ISSUE TITLE
Dark theme: Inconsistencies after changing vs after reload

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#120] opened 2023-03-19 08:58 UTC
See screenshots: https://mamot.fr/@melcore@pouet.chapril.org/110045308238629406

One is "right after changing to dark", the other is "after reloading the page on dark".

**Comment by hugovk** [comment] 2023-03-21 21:18
I can't reproduce on Chrome/Android, Chrome/macOS or Firefox/macOS (desktop and mobile mode), but can reproduce with Safari/macOS (desktop and mobile mode).

It would be good to fix this, but I don't think it's a showstopper: the colours load as expected on the next link click or reload.

cc @septatrix

**Comment by septatrix** [comment] 2023-03-21 23:01
I only have Chrome/Android, Chrome/Linux and Firefox/Linux and cannot reproduce it there. My initial guess is that Safari might not properly respond to a changing `color-scheme: dark;` as that is mostly responsible to style the so called "replaced elements" (selects, inputs, etc) which seem to be affected here. Maybe explicitly setting `color-scheme: light` in the light theme would help such that Safari notices that the value changes though someone else would have to try that.

**Comment by ishan-sharma-3004** [comment] 2024-06-13 23:16
I can't reproduce this on (Chrome, Safari, and Brave)/MacOS. This issue is resolved.

**Comment by pradyunsg** [comment] 2024-06-14 04:44
I can reproduce this on Safari 15.6 (Monterey) but not on Safari 16.5 (Ventura).

15.6:

https://github.com/python/python-docs-theme/assets/3275593/a29d519c-8e04-422b-aed7-b67e4b91560a

16.5:

https://github.com/python/python-docs-theme/assets/3275593/4f97be0b-1fbd-4bcc-b01c-4e5cb9682255

I'm gonna say this was a Safari bug that has been fixed in Safari.

**Closed by pradyunsg** 2024-06-14 04:44 UTC
