### ISSUE TITLE
Faster load ?

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#58] opened 2020-11-04 11:11 UTC
The doc is fast :)

But can it be faster ? → https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdocs.python.org

Typically we load jquery and a few other libs, and we load them soon so they may block the rendering of the page. I think this can be enhanced, but I'm myself particularly bad at front-end things, so if someone want to handle it, go for it :)

**Comment by pradyunsg** [comment] 2020-11-13 20:41
The jQuery load comes from Sphinx directly.

A bunch of external Sphinx plugins directly depend on the jQuery being loaded on every page, so "simply" removing it is going to cause issues if any downstream users want to use them (ReadTheDocs also depends on jQuery for example). :(

https://github.com/sphinx-doc/sphinx/issues/7405 is the relevant issue upstream.

One option at hand is having a theme option to opt-in to disabling jQuery on all pages. This'll allow for faster page load times for users who care (like docs.python.org). :)

**Comment by pradyunsg** [comment] 2020-11-13 20:49
Also, there's parts of this theme that also similarly assume that jQuery is available (I just spotted `$('.inline-search').show(0);`).

**Comment by methane** [comment] 2020-11-14 00:04
I think most JavaScript files can be "defer" ed.
Another problem is `sidebar.js`.  It is ad-hock hack.  It changes layout so redraw happens. User will see sidebar is vibrating on load.

**Comment by methane** [comment] 2020-11-14 00:18
Can we have some simple CSS compiler? We have 5 css files now, but they can be concatinated.

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Fstdtypes.html

**Comment by methane** [comment] 2020-11-14 00:51
I find `language_data.js` is used from only `searchtools.js`, which is included only from `search.html`.
But `language_data.js` is loaded all pages.

**Comment by pradyunsg** [comment] 2020-11-14 11:44
@methane yes, but we can’t be sure of the order of execution then.

There are various implicit dependencies (eg: extensions depending on jQuery,search tools depending on jQuery etc) that are only satisfied by the order that Sphinx gives the files in, which makes deferring not an option that can be used generally in the context of Sphinx documentation.

I’ve tried to do that, and failed, while writing my own documentation theme (Furo).

**Comment by methane** [comment] 2020-11-15 01:45
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

> Scripts with the defer attribute will execute in the order in which they appear in the document.

So we can be sure the order of execution.

**Comment by pradyunsg** [comment] 2021-05-01 10:36
> So we can be sure the order of execution.

Indeed! I stand corrected. :)

Your comment made me add this to Furo (https://pradyunsg.me/furo/changelog/?highlight=script#beta17), but I've had to subsequently remove it (https://pradyunsg.me/furo/changelog/?highlight=script#beta25) because Sphinx search and other extensions were breaking in a subtle way.

---

I'll reiterate what I was trying to say earlier -- the issue is _not_ the Sphinx can't generate pages with this, or that web browsers don't support these things -- but rather that nearly every part of Sphinx's ecosystem assumes that jQuery is available, and that jQuery is hard-coded into the Sphinx's HTML "builder" (https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/builders/html/__init__.py#L315); so overriding it will require weird hacky logic in the HTML templates to avoid including it and things will break in subtle ways.

I don't think this would be easy and, personally, don't think that it'd be worth it; especially given the tiny amounts of volunteer time available for this theme. None the less, I'm not going to be doing this and was mostly just providing a cautionary bit of guidance based on my experience. I'll defer to y'all to decide on this. :)

**Comment by methane** [comment] 2021-05-01 12:31
I didn't mean using `defer` for jQuery.  I meant most JavaScripts other than jQuery.

**Comment by m-aciek** [comment] 2023-03-13 09:10
For what it's worth this PR contains changes that get rid of jQuery in favor of pure JavaScript (assuring compatibility with most recent Sphinx versions).

**Comment by AA-Turner** [comment] 2023-04-20 20:08
#99 now merged! Updating to a jQuery-less Sphinx seems like it'll save ~four fifths of the total page JavaScript, see [this Lighthouse report](https://googlechrome.github.io/lighthouse/treemap/#eyJsaHIiOnsibWFpbkRvY3VtZW50VXJsIjoiaHR0cHM6Ly9kb2NzLnB5dGhvbi5vcmcvMy9saWJyYXJ5L3N0ZHR5cGVzLmh0bWwiLCJmaW5hbFVybCI6Imh0dHBzOi8vZG9jcy5weXRob24ub3JnLzMvbGlicmFyeS9zdGR0eXBlcy5odG1sIiwiZmluYWxEaXNwbGF5ZWRVcmwiOiJodHRwczovL2RvY3MucHl0aG9uLm9yZy8zL2xpYnJhcnkvc3RkdHlwZXMuaHRtbCIsImF1ZGl0cyI6eyJzY3JpcHQtdHJlZW1hcC1kYXRhIjp7ImlkIjoic2NyaXB0LXRyZWVtYXAtZGF0YSIsInRpdGxlIjoiU2NyaXB0IFRyZWVtYXAgRGF0YSIsImRlc2NyaXB0aW9uIjoiVXNlZCBmb3IgdHJlZW1hcCBhcHAiLCJzY29yZSI6bnVsbCwic2NvcmVEaXNwbGF5TW9kZSI6ImluZm9ybWF0aXZlIiwiZGV0YWlscyI6eyJub2RlcyI6W3sibmFtZSI6Imh0dHBzOi8vZG9jcy5weXRob24ub3JnLzMvX3N0YXRpYy9kb2N1bWVudGF0aW9uX29wdGlvbnMuanMiLCJyZXNvdXJjZUJ5dGVzIjo0MjMsInVudXNlZEJ5dGVzIjowfSx7Im5hbWUiOiJodHRwczovL2RvY3MucHl0aG9uLm9yZy8zL19zdGF0aWMvanF1ZXJ5LmpzIiwicmVzb3VyY2VCeXRlcyI6ODk0NzYsInVudXNlZEJ5dGVzIjo1MDMyMn0seyJuYW1lIjoiaHR0cHM6Ly9kb2NzLnB5dGhvbi5vcmcvMy9fc3RhdGljL3VuZGVyc2NvcmUuanMiLCJyZXNvdXJjZUJ5dGVzIjoxOTUzMCwidW51c2VkQnl0ZXMiOjEzMzM5fSx7Im5hbWUiOiJodHRwczovL2RvY3MucHl0aG9uLm9yZy8zL19zdGF0aWMvZG9jdG9vbHMuanMiLCJyZXNvdXJjZUJ5dGVzIjoxMDc2NiwidW51c2VkQnl0ZXMiOjU2NTh9LHsibmFtZSI6Imh0dHBzOi8vZG9jcy5weXRob24ub3JnLzMvX3N0YXRpYy9zaWRlYmFyLmpzIiwicmVzb3VyY2VCeXRlcyI6NDM1MSwidW51c2VkQnl0ZXMiOjExNzF9LHsibmFtZSI6Imh0dHBzOi8vZG9jcy5weXRob24ub3JnLzMvX3N0YXRpYy9jb3B5YnV0dG9uLmpzIiwicmVzb3VyY2VCeXRlcyI6Mjg2OCwidW51c2VkQnl0ZXMiOjgxNn0seyJuYW1lIjoiaHR0cHM6Ly9kb2NzLnB5dGhvbi5vcmcvMy9fc3RhdGljL21lbnUuanMiLCJyZXNvdXJjZUJ5dGVzIjoyMTMyLCJ1bnVzZWRCeXRlcyI6ODU3fSx7Im5hbWUiOiJodHRwczovL2RvY3MucHl0aG9uLm9yZy8zL19zdGF0aWMvc3dpdGNoZXJzLmpzIiwicmVzb3VyY2VCeXRlcyI6NjUwNSwidW51c2VkQnl0ZXMiOjE5MDB9XSwidHlwZSI6InRyZWVtYXAtZGF0YSJ9fX0sImNvbmZpZ1NldHRpbmdzIjp7ImxvY2FsZSI6ImVuLVVTIn19fQ==).

A

**Comment by Privat33r-dev** [comment] 2024-03-17 18:06
![image](https://github.com/python/python-docs-theme/assets/39376984/f156440b-b4df-4530-ac27-cfee7fff6bb1)
I guess the issue is resolved at this point?

**Closed** 2024-03-18 14:27 UTC
