### ISSUE TITLE
no theme named 'python-docs-theme' found (missing theme.conf?)

### ISSUE THREAD

**Issue by zdens** [python/python-docs-theme#45] opened 2020-02-18 12:39 UTC
after installing this theme in virtual environment I've got "Theme error".
I do see "missing theme.conf" in the folder "venv/lib/python3.7/site-packages/python_docs_theme" but "make html" produces an error.
How can this error be fixed?

**Comment by beijersb** [comment] 2020-06-11 22:10
Hmm, i also got this error, after looking around for a while, finally found it:
`conf.py` for your sphinx project should contain something like:
`
extensions = [
    .....,
    'python_docs_theme',
]
`
and further on:
`
html_theme = 'python_docs_theme'
`
Pay special attention to the _ (underscore); don't use - (minus sign).

Works like a charm.
Grtx,
Ben

**Comment by JulienPalard** [comment] 2020-06-15 16:05
Interestingly, cpython just has `html_theme = 'python_docs_theme'`, and we're not having the issue.

**Comment by andy-maier** [comment] 2020-07-21 09:38
I can confirm the issue as described above, for Python 3.8.2 on macOS with Sphinx 3.1.2, and also that it went away after adding `'python_docs_theme'` to `extensions`.

I think the installation instructions on the README page should be updated accordingly (unless someone volunteers to find out why exactly it works without adding `'python_docs_theme'` to `extensions` for the Python 3 docs).

**Comment by andy-maier** [comment] 2020-07-21 09:56
I have created PR #48 to address this issue.

**Comment by JulienPalard** [comment] 2020-07-23 21:20
I checked the following steps:

- Created a venv with Python 3.8.4
- pip installed `Sphinx==3.1.2 python-docs-theme==2020.1`
- ran `sphinx-quickstart`
- ran `make html`
- ran `firefox _build/html/index.html`

and it worked as expected.

**Comment by Mariatta** [comment] 2020-09-14 17:45
For the [core sprint](https://github.com/python/core-sprint) repo, we only added the `html_theme='python_docs_theme'`, using Python 3.8.3 and sphinx 3.2.1.

I think it's not needed to add it to `extensions`.

**Comment by pradyunsg** [comment] 2021-05-01 10:38
I can confirm that the issue here is the `-` vs `_`.

Setting the `html_theme = "python_docs_theme"` tries to import the package `python_docs_theme` as a plugin which obviously works. Similarly, `html_theme = "python-docs-theme"` tries to import the package `python-docs-theme` as a plugin which obviously does not work.

This can be closed IMO.

**Comment by JulienPalard** [comment] 2021-05-01 12:49
Thanks @pradyunsg, and I agree, I'm closing this.

**Closed by JulienPalard** 2021-05-01 12:49 UTC

**Comment by 1C0D** [comment] 2022-04-24 13:15
I'm trying to install this https://github.com/Cartroo/sphinx-theme-graphite
I called the folder (unzipped) graphite and I do in conf.py
```
html_theme = 'graphite'
html_static_path = ["."]
```
but I get the same message graphite no found
I tried directly with the zip too

**Comment by scott-griffiths** [comment] 2022-09-01 07:46
I also had this issue with identical symptoms as the OP. The cause in my case was that Sphinx wasn't installed in the virtualenv that was activated. The Sphinx makefile would still run, but it was finding Sphinx outside of the virtualenv so the errors were very misleading.

Fix was simply

`pip install sphinx`

and then adding it to my `requirements.txt` so that readthedocs would work as expected.

**Comment by peterjpxie** [comment] 2023-01-24 04:53
@scott-griffiths 's fix works for me. I think we need to update https://devguide.python.org/documentation/start-documenting/#building-the-documentation accordingly. 

My environment:

Ubuntu 22.04, it comes with sphinx pre-installed at system path /usr/bin/sphinx-build.

The same issue happens if I follow https://www.sphinx-doc.org/en/master/usage/installation.html#linux to install on Ubuntu16.04:
```
apt-get install python3-sphinx
```

**Comment by goyalyashpal** [comment] 2024-03-28 02:44
> The Sphinx makefile would still run, but it was finding Sphinx outside of the virtualenv so the errors were very misleading.
> \- @ scott-griffiths at https://github.com/python/python-docs-theme/issues/45#issuecomment-1233881707

thanks a lot.

for me, the issue was that i had not activated the `.venv`. 
i am using `pdm` build system, and so-far, i never needed to activate that due to it

but yeah, for `sphinx-build` used by `make html`, `source .venv/Scripts/activate` fixed it :)
looks like it's time to explore `direnv` or the like :D

orrr, better yet, change the makefile lol 😄. no need to activate it again 😆

```diff
- SPHINXBUILD   ?= sphinx-build
+ SPHINXBUILD   ?= pdm run sphinx-build
```
