### ISSUE TITLE
 python-docs-theme ui is make reading hard.

### ISSUE THREAD

**Issue by neuralstring** [python/python-docs-theme#101] opened 2022-12-24 09:43 UTC
After reading rust-lang book, I came to python docs and man it's ugly and painful to read.
Lacking dark-mod, improper separation of heading, bad color scheme and more... 

With little CSS changes, I made it more comfortable for myself,
If you agree to apply these changes to the main repo, I can send a push request.
Here is my changes:

**Before:**
![before](https://user-images.githubusercontent.com/107343209/209430278-bb2d7647-65f3-42d4-a0bf-119c33e05a13.png)
**After:**
![after](https://user-images.githubusercontent.com/107343209/209430282-8379fafe-981f-4f02-89ee-239c398f2ef1.png)

**Comment by ezio-melotti** [comment] 2022-12-25 05:16
This looks like a duplicate of #43 (which also has a PR: #44).

**Comment by SylvKT** [comment] 2023-02-10 02:33
Could you send the CSS for this for others to use?

**Closed** 2023-03-10 08:54 UTC
