### ISSUE TITLE
Make option to invert/modify colors for documentation pages

### ISSUE THREAD

**Issue by brandonardenwalli** [python/python-docs-theme#145] opened 2023-08-14 00:22 UTC
# Feature or enhancement

When reading the docs page in dark mode with night shift, some variables are invisible to see. For example in https://docs.python.org/3/c-api/intro.html#types, `int, long, double and char*` are impossible to read without highlighting the text. This looks to affect any other parts of docs with same coloring too, for example all texts `typedef` on https://docs.python.org/3/c-api/typeobj.html page are practically invisible.

## Environment:
Enable dark mode for system/browser (black background), AND enable night shift. I think there are multiple ways to do so, for example Windows has built in night shift mode to enable screen to be more orange (basically make screen have less blue light). For easiest reproduction, download f.lux and set color to 1900K (or as low as possible). Look at page again, and all the dark blue text, for example the `type` and `typedef` texts, became invisible.

# Pitch

The docs will be much more readable and improve accessibility for bigger audience if the text colors can be modified. I'm not sure how much work this would require, but can be happy to provide feedback. Alternatively, if making the docs text configurable by end user is too much work, just hard code a more friendly color that is readable with dark mode and night shift enabled.

Let me know if you want more information!

**Comment by hugovk** [comment] 2023-08-14 05:12
(I've transferred this from https://github.com/python/cpython to https://github.com/python/python-docs-theme)

Thanks for the report! 

This is a contrast bug, already fixed in https://github.com/python/python-docs-theme/pull/133 and released in https://github.com/python/python-docs-theme/releases/tag/2023.7, but we had to skip that release due to https://github.com/python/python-docs-theme/issues/144/ / https://github.com/python/python-docs-theme/pull/141.

Let's revert https://github.com/python/python-docs-theme/pull/141 so we can make a new release.

**Comment by brandonardenwalli** [comment] 2023-08-15 00:18
Thanks!

Also how to transfer issue? Sorry I made in cpython, I read through https://docs.python.org/3/bugs.html#using-the-python-issue-tracker and it said to make issue at https://github.com/python/cpython/issues. How do I know when to file there versus here?

**Comment by hugovk** [comment] 2023-08-15 09:29
Here's how to transfer, you need write permissions for the repo: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

Yep, it's not obvious the issue is for code in this repo (most styling comes from this theme, but some come from the base Sphinx theme as well), and you did the right thing, thanks again :)

**Comment by brandonardenwalli** [comment] 2023-08-16 01:03
Ok, great to know this https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository!

Thanks for reply!

**Comment by hugovk** [comment] 2023-10-19 18:52
This has now been released and deployed, and the contrast is now improved. Thanks!

**Closed by hugovk** 2023-10-19 18:52 UTC
