### ISSUE TITLE
Search box is wrapping when screen size is reduced

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#7] opened 2017-12-21 19:42 UTC
@freddrake repored that the searchbox is wrapping under the separation line on some screen sizes:

![](https://user-images.githubusercontent.com/588792/34268399-8ab5b64a-e64e-11e7-8f03-e1e90799da02.png)

**Comment by philg314** [comment] 2022-08-01 05:44
This has been fixed in the responsive theme (https://github.com/python/python-docs-theme/pull/46) although that is only used for the docs of Python 3.8 and higher.

But since old Python doc versions don't get updated to new python-docs-theme versions I believe this issue and the linked PR (https://github.com/python/python-docs-theme/pull/33) can be closed.

**Comment by hugovk** [comment] 2023-01-31 19:05
Agreed, fixed on 3.8 and up:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1324225/215857434-89a9b444-a795-4896-9cdd-45e4da670207.png">

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1324225/215857500-07d8eddf-9ed9-41d4-ac17-dc60b3394953.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1324225/215857518-a9be68f6-5bca-4c27-ab02-8a47c3db457e.png">

I can reproduce on 3.7 but that doesn't matter any more. Thanks for retesting @philg314, let's close this and the PR.

**Closed by hugovk** 2023-01-31 19:05 UTC
Labels: bug
