### ISSUE TITLE
Not enough space between list items

### ISSUE THREAD

**Issue by cool-RR** [python/python-docs-theme#47] opened 2020-06-18 11:33 UTC
See this screenshot for documentation that I'm writing as part of PEP 618:

![1](https://user-images.githubusercontent.com/56778/85015415-9a377280-b170-11ea-876c-e4f2caea6bba.jpg)

The list item to the right of the cursor is awkward. I think there should be more space between it and the one above it.

**Comment by JulienPalard** [comment] 2020-06-22 21:25
This is probably rendered as two distinct lists, can you share the rst we can take a look? Also can you check in the DOM if you see two distinct lists?

**Comment by cool-RR** [comment] 2020-06-23 10:29
This has now been merged into Python, so you can see it live here:

https://docs.python.org/3.10/library/functions.html#zip

And you can see the source here: https://raw.githubusercontent.com/python/cpython/master/Doc/library/functions.rst

Search for "Shorter iterables can be padded"

**Comment by cool-RR** [comment] 2020-06-23 10:30
Looking at the DOM, I'm not seeing two distinct lists.

**Comment by hugovk** [comment] 2020-09-16 08:37
There's extra space between the first and second bullet points because the first one ends with a code block.

Code blocks comes with extra CSS to add space below as part of its `div` and `pre`. 

To demonstrate, deleting it shows the usual small gap between bullets:

| Before | After deleting the code block from the DOM |
| - | - |
| ![image](https://user-images.githubusercontent.com/1324225/93312950-80a9d380-f810-11ea-9a58-88751f0685f7.png) | ![image](https://user-images.githubusercontent.com/1324225/93313096-af27ae80-f810-11ea-86b8-e2b67182befd.png) |

**Comment by cool-RR** [comment] 2020-09-16 08:41
@hugovk I understand, and what I'm saying is that there should be more vertical space between list items, regardless of whether they have code blocks in them or not. This is similar to how there's vertical a space between paragraphs. It helps to tell things apart at a glance.

**Comment by hugovk** [comment] 2020-09-16 10:11
Right, there's `1em` below the code blocks, perhaps something like this would help?

```css
li {
    margin-bottom: 1em;
}
```

| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/1324225/93312950-80a9d380-f810-11ea-9a58-88751f0685f7.png) | ![image](https://user-images.githubusercontent.com/1324225/93315062-3ece5c80-f813-11ea-9f8b-c965f27f99da.png) |

**Comment by cool-RR** [comment] 2020-09-16 10:13
Yes, that's perfect.

**Comment by JulienPalard** [comment] 2020-10-08 20:47
I have a vague, old, souvenir of a time where list composed of only small sentences were not spaced, and list composed of long strings were spaced.

IIRC this "feature" was removed because it caused strange visual inconsistencies, typically when a long list had a single long element, triggering the "need spacing" thing.

So ensure it renders correctly for lists of short sentences, like:

-    PEP 584, union operators added to dict;
-    PEP 585, type hinting generics in standard collections;
-    PEP 614, relaxed grammar restrictions on decorators.

and don't resurect the old bug :) (I searched here, in my emails, and on bugs.python.org and can't find where the issue was reported and fixed, sry. If someone remembers something... please link!)

**Comment by pradyunsg** [comment] 2020-11-13 20:46
You can only set that on "simple" lists -- ReStructuredText actually generates a different class for simple (single paragraph) lists and complex (multi paragraph/codeblock etc) lists.

Having a margin for `.simple > li` would be OK in my opinion. See how [Sphinx RTD Theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html#bullet-lists) and [Furo](https://github.com/pradyunsg/furo/blob/3d89d56d5e7722fb450bdde2e1433f53ae1dd3d3/src/furo/assets/styles/content/_lists.sass#L22) handle the same, for reference.

**Comment by hugovk** [comment] 2023-02-16 12:14
Retesting with https://docs.python.org/3.11/library/functions.html#zip I can no longer reproduce this (Chrome 109 on macOS):

<img width="915" alt="image" src="https://user-images.githubusercontent.com/1324225/219360118-ccd9de57-28d7-41b0-aa7a-72dcb577a70a.png">

Inspecting, there's now a `margin-block-start: 14px` before the list item:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1324225/219360357-d89abb3b-ca30-4fc0-9aca-13702bc1d998.png">

Coming from `margin-block-start: 1em` from the "layer user agent style sheet"

<img width="959" alt="image" src="https://user-images.githubusercontent.com/1324225/219360251-7660cce4-ea8d-44d1-af75-f6820791615f.png">

Also looks fine in other browsers.

<details>
<summary>Safari</summary>


<img width="792" alt="image" src="https://user-images.githubusercontent.com/1324225/219361283-6cf62417-5bcf-4581-ae9d-8fccc0613563.png">


</details>


<details>
<summary>Firefox</summary>


<img width="769" alt="image" src="https://user-images.githubusercontent.com/1324225/219361162-7aa9261a-9627-4ca4-9488-8233e89f8cc8.png">



</details>

<details>
<summary>Opera</summary>


<img width="827" alt="image" src="https://user-images.githubusercontent.com/1324225/219361076-8f54ddb0-2f59-4266-af5b-ae9ad675393a.png">

</details>

And Chrome on Android.

<details>
<summary>Chrome on Android</summary>

![image](https://user-images.githubusercontent.com/1324225/219361897-5c737c52-d42e-42ba-943f-1f3d7ae74b25.png)

</details>

Let's close this, and can re-open if it's reproducible on some other browser/OS. 

Thanks anyway for the report!

**Closed by hugovk** 2023-02-16 12:14 UTC

**Comment by cool-RR** [comment] 2023-02-16 12:16
Confirmed it doesn't happen on my browser anymore. Thank you.
